baseURL = 'https://lemontroyal.github.io'
languageCode = 'fr-fr'
title = 'Le Mont Royal'
theme = "blowfish"

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 1

[caches]
    [caches.images]
        dir = ':cacheDir/images'